name: Build Vue2 Project

# 只允许手动触发工作流
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v4
    
    # 设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14.16'  # 根据你的项目需求调整版本
        cache: 'npm'
    
    # 安装依赖
    - name: Install dependencies
      run: npm install
    
    # 构建项目
    - name: Build project
      run: npm run build
    
    # 创建构建产物的压缩包
    - name: Create build artifact
      run: |
        cd dist  # Vue2默认构建目录，如果不同请修改
        zip -r ../vue2-build-$(date +%Y%m%d-%H%M%S).zip .
        cd ..
    
    # 上传构建产物作为artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: vue2-build-${{ github.run_number }}
        path: vue2-build-*.zip
        retention-days: 30  # 保留30天
